# Generated by Django 6.0 on 2025-12-25 10:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tax_percent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
